kind: pipeline
type: kubernetes
name: simple-print

steps:
  - name: list s3 buckets
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - aws s3 ls
      - aws s3 cp s3://testcmcbucket/test.json .
      - cat test.json
      - echo ${TESTING}
    when:
      event:
        - promote
      target: 
        - prod