kind: pipeline
type: kubernetes
name: simple-print

steps:
  - name: list s3 buckets
    image: banst/awscli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - echo "Hello, Drone CI/CD !"
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY_ID
      - aws s3 ls
      - exit 1